language: minimal

services:
- docker

script:
- sudo make dist

before_deploy:
  - cd dist && sudo ../ci/hashgen.sh && cd ..

deploy:
  provider: releases
  api_key:
    secure: PR/xN09hqqhCXLMXLlNgVMK9zlRJwmkfQxRJiSBWtYZ1quNwS5BFIkZxRJrC9LYgZuxTeLEzR4RZqKxgaE0G16An+YAc9sOw2ITfIQbPvgghZ+TOxxAPUe3a5ah9WmG9KFJ7/gKxoqlzYKCEL9ybu+y4vdOhuHAXlPcOpt4JbHPFcgHcK3zPRZzKvE8F+ZbQhYwZloAnq7/n0354+K4TQD6FQ17h/LW0AEvc69wGs8RIgxk67nHOBw6xbWe1hisGqENm5HIrbvx3CUCCahofVcCmuoCgulPraf+7VnfF+vmFJgxC2mYl9GHc/HrKK0vgIZmrH7ovYLPTpjYUTB9ih1yWjfBLsUyX7SmRbXP67Y24krN7/0FSZ9tlU6xmwBfUWEcplrbqaqQjFkavig9WRoPCrQWV3RWtnf021twjzGDdi6fcHeIyF4joWkU/zwp9lysNbFpSnsWaWm4c55R2Hr9cgj03BU58SuL2iMOx4J90oS2ls93ztZulK36qOKWXwgISmdp8XXQOV5OZvSLEgh6CgMLCr4FmRakAGTtV8YPtmaY84HF5V4TVEglX6VCnqxrun55g04tPeH3eQCcSZt44jJakYbCZwxL/3GT3Ah8cPbHoSi29H6EjaLQgTx3xPagd5cLmqEmR3Cx/VGpeuZ32jEKk7s2/P03RbwlH/Ls=
  file_glob: true
  file: 
    - dist/*.tgz
    - dist/*.tgz.sha256
  skip_cleanup: true
  on:
    tags: true