language: minimal

services:
- docker

script:
- sudo make dist

deploy:
  provider: releases
  api_key:
    secure: OQ468DeJyeOg6GC/4OJrrnPTZegPyq46QYeDc+P7Yw2cMwSlRnqprNiv/1kTpCDFIZXuceR/jPaQsd5idNJeF1odqthfkli87FgnJWOykkpJWBp4O0yylOxNZnHZzsP+o35owqDaYpdE4HKZBommzQRBG4MyjztIWLabOl/XzhRMf6J3xSzWi7SppQb4Fp3KYtKo9t7ENuC1Vx4B9UdGKHLVc6STGouBxznKGNcMo6fX+5j7t1FzqkKIM1uuMl1Lxe/LwAm9UpUKvWmv3bR1gD/70sysvdtWPbCclfR5CpLxVNm1DLGJufEF9KIZ4v/TBJoRmmekdtQ4x+PEy/F+5FY1x0Mlnk5gbfiGCay8sPnmEGhWrdc9PanAARMIFlSGNRqCWvW+OWd+xqfZwSC6zJL6SVGWzUxQXjlqHbqwsLy7ey0554wL4OuR/fYHmWeFrRyxGo2xXm5j/BVyooHRgK5dOhNkGNnFnkDsCZO/Cp6pn9QP/HfnVFZDnx6zivEqPDMP/ZtrRX/Um9NbzU7ISq3RUkGuQk2vQyHVGYYQGrKuUYVZ/G0QHUevEMy6ZRMoSLZZ+ZS9sOebWry8x/EjQ1ZdZujp6g5ImdRwSSOI45QbNhxfzWeYb1Vb6WA8mK5jUyxH7+IHNix3e6lHzDHhnyq1OUh++An6NlMn5wrRt/U=
  file_glob: true
  file: dist/*.tgz
  skip_cleanup: true
  on:
    tags: true