language: minimal

services:
- docker

before_install:
- docker pull quay.io/solo-io/packer-builder-arm-image:v0.1.4.5

script:
- sudo make faasd
- sudo make faasd-inlets-oss
- sudo make faasd-inlets-pro